### ISSUE TITLE
Status of this repo vs textmate-yara ? 

### ISSUE THREAD

**Issue by wesinator** [infosec-intern/vscode-yara-abandoned#2]
Can you give guidance on the status of this repo vs. https://github.com/infosec-intern/textmate-yara ? 
I noticed textmate-yara is the version still provided in Visual Studio code extensions

This repo's branch has an updated version that already had fixes for something I'd fixed in https://github.com/infosec-intern/textmate-yara/pull/29 

Can you consolidate / archive as needed ?
Obviously textmate-yara is still in use currently

**Comment by infosec-intern** [comment]
Funny, I didn't think anyone would see this repo until I was ready to release it. The textmate-yara repo is effectively in indefinite maintenance mode, and the next major version of the extension will be released from this repository.

This repo is intended to be an upgrade of the textmate-yara repo; it accomplishes the same goal, but with better flexibility and more features than what I was able to provide in textmate-yara. I've had it in development for a long time but due to life/work things taking precedent, I haven't been able to consistently work on it for a long time. There is a GitHub Pages site that has the basic functionality outlined at https://infosec-intern.github.io/vscode-yara/, but I'm still working on making installation robust and transparent to the user, and ensuring the extension can recover if the language server dies for whatever reason.

Unfortunately, I can't really give a good timeframe of when this will be finished, since this is just me working on it when I have enough free time.

**Comment by wesinator** [comment]
no problem, thanks !

Happy new year

**Comment by infosec-intern** [comment]
You too!

**Comment by infosec-intern** [comment]
Just giving another update on this (I'm sorry!). I've decided to abandon this particular version of the project. It's been over a year since the first update and, while I've made progress on the language server, other unforeseen problems keep popping up with this implementation.

The good news is that I've learned a whole lot about Typescript in the meantime, and I should be able to port most of the features I previously thought could only be done in Python into the existing Typescript-based extension (currently located at [textmate-yara](https://github.com/infosec-intern/textmate-yara/)).

Soon I will update the name/README of this repository to make this all more prominent, but I have moved the Python-based language server into its own repository ([ch0mler/yara-language-server](https://github.com/ch0mler/yara-language-server/)) and uploaded the package to PyPi ([yara-language-server](https://pypi.org/project/yara-language-server/)) in case anyone is interested in continuing that work or re-implementing it in another language or for another platform. I'll also be renaming the old textmate-yara repository to vscode-yara, since that is a significantly more obvious name to find.

I apologize for all the confusion over the last few years, but I hope that these changes will help make the project better for everyone.
